name=MKE_I2C_RFID
version=1.0.0
author=MakerEdu
maintainer=MakerEdu
sentence=Library for MKE I2C RFID RC522 module
paragraph=Provides an easy interface to control the MakerEdu I2C RFID RC522 module.
category=Communication
url=https://github.com/MakerEdu
architectures=*
includes=MKE_I2C_RFID.h
